ALTER TABLE ROLES
ALTER COLUMN role_id ADD GENERATED ALWAYS AS IDENTITY;


INSERT INTO ROLES(role_desc) values ('ADMIN'),('AUDITOR'),('ACCOUNTANT');
INSERT INTO USER_ROLES(user_id,role_id) values (4,1),(4,2),(4,3);

INSERT INTO PERMISSION(permission_desc)  VALUES ('DB-CREATE'),('DB-QUERY');
INSERT INTO PERMISSION_USER(PERMISSION_ID,USER_ID) VALUES (1,4),(2,4);